# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginForm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginForm

  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  target 'LoginFormTests' do
  
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoginFormUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
